using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;
namespace SoundLeaf
{
    internal static class TextCatalog
    {
        private static readonly Dictionary<string, string[]> entries = new Dictionary<string, string[]>();
        private static volatile string language = "ru";
        private static Regex known;
        private static readonly Dictionary<string, string> ids = new Dictionary<string, string>();
        internal static string Language { get { return language; } }
        internal static void SetLanguage(string value) { language = value == "de" || value == "ru" ? value : "en"; }
        internal static string T(string id) { string[] value; return entries.TryGetValue(id, out value) ? value[language == "ru" ? 0 : language == "de" ? 2 : 1] : id; }
        internal static string Translate(string text) { if (string.IsNullOrEmpty(text)) return text; string id; if (ids.TryGetValue(text, out id)) return T(id); return known.Replace(text, delegate(Match m) { return T(ids[m.Value]); }); }
        internal static bool Complete { get { foreach (var value in entries.Values) if (value.Length != 3 || Array.Exists(value, string.IsNullOrEmpty)) return false; return true; } }
        private static void Add(string id, string ru, string en, string de) { entries.Add(id, new[] { ru, en, de }); }
        static TextCatalog()
        {
            Add("message.0", "SoundLeaf — ошибка", "SoundLeaf — error", "SoundLeaf — Fehler");
            Add("message.1", "Запись ещё не сохранена", "Recording not saved yet", "Aufnahme noch nicht gespeichert");
            Add("message.2", "Начать новую запись", "Start a new recording", "Neue Aufnahme starten");
            Add("message.3", "Начать запись только в WAV", "Start WAV-only recording", "Nur WAV aufnehmen");
            Add("message.4", "Проверка перед записью", "Preflight checks", "Vorprüfung");
            Add("message.5", "Пауза", "Pause", "Pause");
            Add("message.6", "Остановить и сохранить", "Stop and save", "Stoppen und speichern");
            Add("message.7", "Собрать незавершённые записи", "Recover unfinished sessions", "Unvollständige Sitzungen wiederherstellen");
            Add("message.8", "Результат записи", "Recording result", "Aufnahmeergebnis");
            Add("message.9", "Незавершённых сессий: ", "Unfinished sessions: ", "Unvollständige Sitzungen: ");
            Add("message.10", "SoundLeaf — результат", "SoundLeaf — result", "SoundLeaf — Ergebnis");
            Add("message.11", "Открыть последний итоговый файл", "Open last verified file", "Letzte geprüfte Datei öffnen");
            Add("message.12", "Незавершённых сессий: 0", "Unfinished sessions: 0", "Unvollständige Sitzungen: 0");
            Add("message.13", "Автозапуск с Windows", "Start with Windows", "Mit Windows starten");
            Add("message.14", "Выход", "Exit", "Beenden");
            Add("message.15", "Открыть папку записей", "Open recordings folder", "Aufnahmeordner öffnen");
            Add("message.16", "Открыть журнал ошибок", "Open error log", "Fehlerprotokoll öffnen");
            Add("message.17", "SoundLeaf — запуск", "SoundLeaf — starting", "SoundLeaf — Start");
            Add("message.18", "SoundLeaf — незавершённые записи", "SoundLeaf — unfinished sessions", "SoundLeaf — unvollständige Sitzungen");
            Add("message.19", "Найдено сессий: ", "Sessions found: ", "Gefundene Sitzungen: ");
            Add("message.20", ". После остановки текущей записи выберите «Собрать незавершённые записи».", ". After stopping, select “Recover unfinished sessions”.", ". Nach dem Stoppen „Unvollständige Sitzungen wiederherstellen“ wählen.");
            Add("message.21", "Запуск", "Starting", "Start");
            Add("message.22", "Предупреждение: ", "Warning: ", "Warnung: ");
            Add("message.23", "Проверки пройдены", "Checks passed", "Prüfungen bestanden");
            Add("message.24", "Открыть папку итоговых WAV", "Open final WAV folder", "Ordner der fertigen WAV öffnen");
            Add("message.25", "Готово: ", "Ready: ", "Fertig: ");
            Add("message.26", " · только WAV", " · WAV only", " · nur WAV");
            Add("message.27", "Продолжить запись", "Resume recording", "Aufnahme fortsetzen");
            Add("message.28", "запись", "recording", "Aufnahme");
            Add("message.29", "пауза", "paused", "Pause");
            Add("message.30", "запуск", "starting", "Start");
            Add("message.31", "ошибка — откройте журнал", "error — open log", "Fehler — Protokoll öffnen");
            Add("message.32", "не удалось проверить прошлые записи", "previous recordings could not be checked", "Frühere Aufnahmen konnten nicht geprüft werden");
            Add("message.33", "есть незавершённые записи: ", "unfinished sessions: ", "Unvollständige Sitzungen: ");
            Add("message.34", "WAV сохранён; MKV не создавался", "WAV saved; no MKV was created", "WAV gespeichert; keine MKV erstellt");
            Add("message.35", "готово: ", "ready: ", "Fertig: ");
            Add("message.36", "остановлен; ", "stopped; ", "Gestoppt; ");
            Add("message.37", " · тишина", " · silence", " · Stille");
            Add("message.38", "Незавершённых сессий не найдено.", "No unfinished sessions found.", "Keine unvollständigen Sitzungen gefunden.");
            Add("message.39", "Собрать сессий: ", "Recover sessions: ", "Sitzungen wiederherstellen: ");
            Add("message.40", "? Исходные WAV сохранятся в резервной папке после проверки итога.", "? Original WAV files will be archived after the output is verified.", "? Original-WAV werden nach der Ergebnisprüfung archiviert.");
            Add("message.41", "SoundLeaf — восстановление", "SoundLeaf — recovery", "SoundLeaf — Wiederherstellung");
            Add("message.42", "Восстановление", "Recovery", "Wiederherstellung");
            Add("message.43", "Собрано сессий: ", "Recovered sessions: ", "Wiederhergestellte Sitzungen: ");
            Add("message.44", "; ошибок: ", "; errors: ", "; Fehler: ");
            Add("message.45", "Проверенных итоговых файлов: ", "Verified output files: ", "Geprüfte Ergebnisdateien: ");
            Add("message.46", "Не удалось проверить незавершённые записи", "Could not check unfinished sessions", "Unvollständige Sitzungen konnten nicht geprüft werden");
            Add("message.47", "SoundLeaf будет запускаться при входе в Windows.", "SoundLeaf will start when you sign in to Windows.", "SoundLeaf startet bei der Windows-Anmeldung.");
            Add("message.48", "Автозапуск отключён.", "Startup disabled.", "Autostart deaktiviert.");
            Add("message.49", "Не удалось изменить автозапуск: ", "Could not change startup: ", "Autostart konnte nicht geändert werden: ");
            Add("message.50", "Запуск отменён; запись не начата", "Startup cancelled; no recording started", "Start abgebrochen; keine Aufnahme begonnen");
            Add("message.51", "Запись системного вывода", "Recording system output", "Systemausgabe aufnehmen");
            Add("message.52", "Запись; звук поступал", "Recording; audio received", "Aufnahme; Ton empfangen");
            Add("message.53", "Запись; пока тишина", "Recording; silence so far", "Aufnahme; bisher Stille");
            Add("message.54", "Сохранение", "Saving", "Speichern");
            Add("message.55", "Аудиоданные не получены. Временный WAV оставлен.", "No audio data received. Temporary WAV retained.", "Keine Audiodaten empfangen. Temporäre WAV bleibt erhalten.");
            Add("message.56", "Проверка WAV и фиксация результата", "Checking WAV and committing result", "WAV prüfen und Ergebnis festhalten");
            Add("message.57", "Не удалось открыть аудиоустройство.", "Could not open audio device.", "Audiogerät konnte nicht geöffnet werden.");
            Add("message.58", "Windows сообщила о разрыве аудиопотока; сохранённый звук стоит проверить.", "Windows reported an audio discontinuity; check the saved sound.", "Windows meldete eine Audiounterbrechung; gespeicherten Ton prüfen.");
            Add("message.59", "WAV сохранён; MKV не создавался. Частей: ", "WAV saved; no MKV was created. Parts: ", "WAV gespeichert; keine MKV erstellt. Teile: ");
            Add("message.60", " — сохранён и проверен", " — saved and verified", " — gespeichert und geprüft");
            Add("message.61", "Сохранено; за время записи был только тихий сигнал или тишина", "Saved; only quiet signal or silence was recorded", "Gespeichert; nur leises Signal oder Stille");
            Add("message.62", "Кодировщик не успевает. Резервный WAV сохранён.", "Encoder cannot keep up. Backup WAV retained.", "Encoder kommt nicht nach. WAV-Sicherung bleibt erhalten.");
            Add("message.63", "FFmpeg не завершился вовремя. WAV сохранён.", "FFmpeg did not finish in time. WAV retained.", "FFmpeg nicht rechtzeitig beendet. WAV bleibt erhalten.");
            Add("message.64", "Ошибка кодирования; WAV сохранён. ", "Encoding error; WAV retained. ", "Kodierungsfehler; WAV bleibt erhalten. ");
            Add("message.65", "Завершение кодирования", "Finishing encoding", "Kodierung abschließen");
            Add("message.66", "Превышено время сохранения MKV. WAV оставлен.", "MKV save timeout exceeded. WAV retained.", "MKV-Speicherzeit überschritten. WAV bleibt erhalten.");
            Add("message.67", "Проверка части MKV", "Checking MKV part", "MKV-Teil prüfen");
            Add("message.68", "Длительность MKV не совпадает с WAV. WAV сохранён.", "MKV duration differs from WAV. WAV retained.", "MKV-Dauer weicht von WAV ab. WAV bleibt erhalten.");
            Add("message.69", "FFmpeg превысил время ожидания. Исходный WAV сохранён.", "FFmpeg timeout. Original WAV retained.", "FFmpeg-Zeitlimit. Original-WAV bleibt erhalten.");
            Add("message.70", "Проверка аудио не пройдена: ", "Audio verification failed: ", "Audioprüfung fehlgeschlagen: ");
            Add("message.71", "Файл не содержит декодируемого аудио.", "File contains no decodable audio.", "Datei enthält kein dekodierbares Audio.");
            Add("message.72", "FFmpeg отсутствует в tools. WAV сохранён.", "FFmpeg missing from tools. WAV retained.", "FFmpeg fehlt in tools. WAV bleibt erhalten.");
            Add("message.73", "MKV уже существует; перезапись запрещена.", "MKV already exists; overwrite prohibited.", "MKV existiert bereits; Überschreiben verboten.");
            Add("message.74", "Кодирование резервного WAV", "Encoding backup WAV", "WAV-Sicherung kodieren");
            Add("message.75", "MKV не создан. WAV сохранён. ", "MKV not created. WAV retained. ", "Keine MKV erstellt. WAV bleibt erhalten. ");
            Add("message.76", "Длительности WAV и MKV различаются; временный MKV и исходный WAV сохранены.", "WAV and MKV durations differ; temporary output and WAV retained.", "WAV- und MKV-Dauer unterschiedlich; temporäres Ergebnis und WAV bleiben erhalten.");
            Add("message.77", "FFmpeg отсутствует; части сохранены.", "FFmpeg missing; parts retained.", "FFmpeg fehlt; Teile bleiben erhalten.");
            Add("message.78", "Неверное имя первой части MKV.", "Invalid first MKV part name.", "Ungültiger Name des ersten MKV-Teils.");
            Add("message.79", "Итоговый MKV уже существует; части сохранены.", "Final MKV already exists; parts retained.", "Ergebnis-MKV existiert bereits; Teile bleiben erhalten.");
            Add("message.80", "Часть MKV отсутствует; WAV сохранены.", "MKV part missing; WAV retained.", "MKV-Teil fehlt; WAV bleibt erhalten.");
            Add("message.81", "Части MKV находятся в разных папках.", "MKV parts are in different folders.", "MKV-Teile liegen in unterschiedlichen Ordnern.");
            Add("message.82", "Апостроф в пути MKV не поддерживается.", "Apostrophe in MKV path is unsupported.", "Apostroph im MKV-Pfad nicht unterstützt.");
            Add("message.83", "Объединение частей", "Combining parts", "Teile zusammenführen");
            Add("message.84", "Объединение MKV не удалось; части и WAV сохранены. ", "MKV join failed; parts and WAV retained. ", "MKV-Zusammenführung fehlgeschlagen; Teile und WAV bleiben erhalten. ");
            Add("message.85", "Проверка итогового файла", "Checking final file", "Ergebnisdatei prüfen");
            Add("message.86", "Длительность объединённого MKV неверна; части и WAV сохранены.", "Joined MKV duration is wrong; parts and WAV retained.", "Dauer der zusammengeführten MKV falsch; Teile und WAV bleiben erhalten.");
            Add("message.87", "Папка проверки уже существует.", "Probe folder already exists.", "Prüfordner existiert bereits.");
            Add("message.88", "Проверка записи в папку не пройдена.", "Folder write check failed.", "Schreibprüfung des Ordners fehlgeschlagen.");
            Add("message.89", "Свободного места меньше 256 МиБ. Запись не начата.", "Less than 256 MiB free. Recording not started.", "Weniger als 256 MiB frei. Aufnahme nicht gestartet.");
            Add("message.90", "Не удалось определить свободное место; запись в папку проверена.", "Free space could not be measured; folder write check passed.", "Freier Speicher nicht messbar; Schreibprüfung bestanden.");
            Add("message.91", "Свободного места меньше 1 ГиБ. Его может не хватить на всю запись.", "Less than 1 GiB free. Space may run out during recording.", "Weniger als 1 GiB frei. Speicher kann während der Aufnahme ausgehen.");
            Add("message.92", "FFmpeg отсутствует в tools.", "FFmpeg missing from tools.", "FFmpeg fehlt in tools.");
            Add("message.93", "Тест кодирования не пройден: ", "Encoding test failed: ", "Kodierungsprüfung fehlgeschlagen: ");
            Add("message.94", "Проверка тестового аудио не пройдена.", "Test audio verification failed.", "Prüfung des Testaudios fehlgeschlagen.");
            Add("message.95", " недоступен: ", " unavailable: ", " nicht verfügbar: ");
            Add("message.96", " Для резервной записи выберите «Начать запись только в WAV».", " To record without encoding, select “Start WAV-only recording”.", " Für Aufnahme ohne Encoder „Nur WAV aufnehmen“ wählen.");
            Add("message.97", "Запись не начата: ", "Recording not started: ", "Aufnahme nicht gestartet: ");
            Add("message.98", "Нет WAV для фиксации результата.", "No WAV files to commit.", "Keine WAV zum Festhalten des Ergebnisses.");
            Add("message.99", "Неверный идентификатор WAV-сессии.", "Invalid WAV session identifier.", "Ungültige WAV-Sitzungskennung.");
            Add("message.100", "WAV вне папки приложения.", "WAV outside application folder.", "WAV außerhalb des Programmordners.");
            Add("message.101", "Папка состояния не должна быть ссылкой.", "State folder must not be a link.", "Statusordner darf keine Verknüpfung sein.");
            Add("message.102", "Эта WAV-сессия намеренно завершена; автоматическое восстановление запрещено.", "This WAV session was deliberately completed; automatic recovery prohibited.", "Diese WAV-Sitzung wurde bewusst abgeschlossen; automatische Wiederherstellung verboten.");
            Add("message.103", "Неоднозначный набор частей; исходники оставлены.", "Ambiguous parts; originals retained.", "Mehrdeutige Teile; Originale bleiben erhalten.");
            Add("message.104", "Пропущена часть записи; автоматическая сборка запрещена.", "Missing recording part; automatic recovery prohibited.", "Aufnahmeteil fehlt; automatische Wiederherstellung verboten.");
            Add("message.105", "Итоговый файл уже существует; перезапись и очистка запрещены.", "Output already exists; overwrite and cleanup prohibited.", "Ergebnis existiert bereits; Überschreiben und Bereinigung verboten.");
            Add("message.106", "Форматы частей различаются; исходники оставлены.", "Part formats differ; originals retained.", "Teilformate unterschiedlich; Originale bleiben erhalten.");
            Add("message.107", "Подготовка части ", "Preparing part ", "Teil vorbereiten ");
            Add("message.108", "Итоговая длительность неверна; исходники оставлены.", "Output duration is wrong; originals retained.", "Ergebnisdauer falsch; Originale bleiben erhalten.");
            Add("control", "Управление", "Controls", "Steuerung");
            Add("recordings", "Записи", "Recordings", "Aufnahmen");
            Add("settings", "Настройки", "Settings", "Einstellungen");
            Add("format", "Формат", "Format", "Format");
            Add("bitrate", "Битрейт", "Bitrate", "Bitrate");
            Add("language", "Язык", "Language", "Sprache");
            Add("theme", "Тема", "Theme", "Design");
            Add("system", "Как в Windows", "Follow Windows", "Wie Windows");
            Add("light", "Светлая листва", "Light foliage", "Helles Laub");
            Add("dark", "Тёмный лес", "Dark forest", "Dunkler Wald");
            Add("folder", "Папка сохранения", "Save folder", "Speicherordner");
            Add("choose", "Выбрать папку", "Choose folder", "Ordner wählen");
            Add("open", "Открыть", "Open", "Öffnen");
            Add("reveal", "Показать в папке", "Show in folder", "Im Ordner anzeigen");
            Add("convert", "Пересохранить", "Save in another format", "In anderem Format speichern");
            Add("refresh", "Обновить список", "Refresh list", "Liste aktualisieren");
            Add("verified", "Проверено", "Verified", "Geprüft");
            Add("existing", "Существующий файл; не проверен", "Existing file; not verified", "Vorhandene Datei; nicht geprüft");
            Add("loading", "Загрузка…", "Loading…", "Laden…");
            Add("empty", "Записей пока нет", "No recordings yet", "Noch keine Aufnahmen");
            Add("channels", "Opus: моно, 48 кГц, целевой VBR. MP3/M4A/AAC: 48 кГц, до двух каналов. Резервный WAV — исходный звук.", "Opus: mono, 48 kHz, target VBR. MP3/M4A/AAC: 48 kHz, up to two channels. Backup WAV retains source audio.", "Opus: mono, 48 kHz, VBR-Ziel. MP3/M4A/AAC: 48 kHz, bis zwei Kanäle. WAV-Sicherung behält Originalton.");
            Add("restored", "Настройки повреждены: восстановлен MKV/AAC 192.", "Settings damaged: MKV/AAC 192 restored.", "Einstellungen beschädigt: MKV/AAC 192 wiederhergestellt.");
            Add("educational", "Учебный проект · системный звук Windows", "Educational project · Windows system audio", "Lernprojekt · Windows-Systemaudio");
            Add("conversionWarning", "Исходник останется нетронутым. Повторное кодирование сжатого звука не повышает качество.", "Original stays untouched. Re-encoding compressed audio does not improve quality.", "Original bleibt unverändert. Erneutes Kodieren verbessert komprimiertes Audio nicht.");
            Add("export", "Создать новый файл", "Create new file", "Neue Datei erstellen");
            Add("back", "Назад", "Back", "Zurück");
            Add("close", "Скрыть панель", "Hide panel", "Panel ausblenden");
            Add("stopped", "Остановлено", "Stopped", "Gestoppt");
            Add("size", "Размер", "Size", "Größe");
            Add("duration", "Длительность", "Duration", "Dauer");
            Add("conversionDone", "Новый файл сохранён и проверен", "New file saved and verified", "Neue Datei gespeichert und geprüft");
            Add("conversionBusy", "Пересохранение и проверка…", "Converting and verifying…", "Konvertieren und prüfen…");
            Add("exit", "Выход", "Exit", "Beenden");
            Add("autostart", "Автозапуск с Windows", "Start with Windows", "Mit Windows starten");
            Add("unknown", "Неизвестно", "Unknown", "Unbekannt");
            Add("startupForeign", "Имя автозапуска занято другой установкой; её запись оставлена без изменений.", "Startup name belongs to another installation; its entry was not changed.", "Autostartname gehört zu einer anderen Installation; Eintrag bleibt unverändert.");
            Add("extensionCollision", "Итог уже существует или расширение неверно; исходник сохранён.", "Output exists or extension is wrong; original retained.", "Ergebnis existiert bereits oder Dateiendung falsch; Original bleibt erhalten.");
            Add("collision", "Итог уже существует или отсутствуют WAV-части.", "Output collision or missing WAV parts.", "Ergebnis existiert bereits oder WAV-Teile fehlen.");
            Add("incompatible", "Форматы WAV-частей несовместимы.", "Incompatible WAV parts.", "WAV-Teile haben inkompatible Formate.");
            Add("encoderTimeout", "Кодировщик не завершился вовремя; WAV сохранён.", "Encoder timeout; WAV retained.", "Encoder-Zeitlimit erreicht; WAV bleibt erhalten.");
            Add("feedTimeout", "Передача звука не завершилась вовремя; WAV сохранён.", "PCM feeder timeout; WAV retained.", "PCM-Übertragung hat Zeitlimit erreicht; WAV bleibt erhalten.");
            Add("feedFailed", "Пересборка звука не удалась; WAV сохранён.", "PCM rebuild failed; WAV retained.", "PCM-Neuerstellung fehlgeschlagen; WAV bleibt erhalten.");
            Add("encodeFailed", "Кодирование не удалось; WAV сохранён. ", "Encoding failed; WAV retained. ", "Kodierung fehlgeschlagen; WAV bleibt erhalten. ");
            Add("originalCollision", "Итог уже существует; исходник оставлен без изменений.", "Output already exists; original retained.", "Ergebnis existiert bereits; Original bleibt unverändert.");
            Add("convertFailed", "Пересохранение не удалось; исходник сохранён. ", "Conversion failed; original retained. ", "Konvertierung fehlgeschlagen; Original bleibt erhalten. ");
            Add("audioMetadata", "Не удалось определить параметры аудиопотока.", "Audio stream metadata unavailable.", "Audiostream-Metadaten nicht verfügbar.");
            Add("durationFailed", "Длительность результата неверна; исходники сохранены.", "Encoded duration differs from WAV; originals retained.", "Ergebnisdauer stimmt nicht; Originale bleiben erhalten.");
            Add("diagnostic.0", "Неверный профиль записи.", "Invalid recording profile.", "Ungültiges Aufnahmeprofil.");
            Add("diagnostic.1", "Папка состояния не должна быть ссылкой.", "State directory must not be a link.", "Statusordner darf keine Verknüpfung sein.");
            Add("diagnostic.2", "Папка метаданных является ссылкой; операция запрещена.", "Metadata directory link rejected.", "Metadatenordner ist eine Verknüpfung; Vorgang abgelehnt.");
            Add("diagnostic.3", "Файл метаданных является ссылкой; операция запрещена.", "Metadata link rejected.", "Metadatendatei ist eine Verknüpfung; Vorgang abgelehnt.");
            Add("diagnostic.4", "Файл метаданных слишком большой.", "Metadata too large.", "Metadatendatei ist zu groß.");
            Add("diagnostic.5", "Неверные настройки.", "Invalid settings.", "Ungültige Einstellungen.");
            Add("diagnostic.6", "Неверная папка сохранения.", "Invalid output folder.", "Ungültiger Ausgabeordner.");
            Add("diagnostic.7", "Слишком много папок в списке записей.", "Too many library folders.", "Zu viele Bibliotheksordner.");
            Add("diagnostic.8", "Неверная папка списка записей.", "Invalid library folder.", "Ungültiger Bibliotheksordner.");
            Add("diagnostic.9", "Итог находится вне папки хранения.", "Result outside application folder.", "Ergebnis liegt außerhalb des Speicherordners.");
            Add("diagnostic.10", "Неверная рабочая папка восстановления.", "Invalid recovery staging directory.", "Ungültiger Arbeitsordner für Wiederherstellung.");
            Add("diagnostic.11", "Превышено время работы кодировщика.", "Live encoder timeout.", "Zeitlimit des Live-Encoders überschritten.");
            Add("diagnostic.12", "Неверный путь.", "Invalid path.", "Ungültiger Pfad.");
            Add("diagnostic.13", "Требуются как минимум две части.", "At least two parts are required.", "Mindestens zwei Teile erforderlich.");
            Add("diagnostic.14", "Нет WAV-частей для архивации.", "No WAV parts to archive.", "Keine WAV-Teile zum Archivieren.");
            Add("diagnostic.15", "Неверное имя части записи.", "Invalid part name.", "Ungültiger Name eines Aufnahmeteils.");
            Add("diagnostic.16", "Резервный WAV уже существует; ничего не перезаписано.", "Backup WAV already exists; nothing overwritten.", "WAV-Sicherung existiert bereits; nichts überschrieben.");
            Add("diagnostic.17", "Резервный MKV уже существует; ничего не перезаписано.", "Backup MKV already exists; nothing overwritten.", "MKV-Sicherung existiert bereits; nichts überschrieben.");
            Add("diagnostic.18", "Заголовок формата WAV слишком короткий.", "WAV format is too short.", "WAV-Formatkopf zu kurz.");
            Add("diagnostic.19", "Неполный заголовок WAVEFORMATEXTENSIBLE.", "Incomplete WAVEFORMATEXTENSIBLE header.", "Unvollständiger WAVEFORMATEXTENSIBLE-Kopf.");
            Add("diagnostic.20", "Неподдерживаемый подформат WAV.", "Unsupported WAV subformat.", "Nicht unterstütztes WAV-Unterformat.");
            Add("diagnostic.21", "Неподдерживаемый или противоречивый формат PCM/float.", "Unsupported or inconsistent PCM/float audio format.", "Nicht unterstütztes oder widersprüchliches PCM/Float-Format.");
            Add("diagnostic.22", "Аудиоданные не выровнены по кадрам.", "Unaligned audio data.", "Audiodaten nicht an Frames ausgerichtet.");
            Add("diagnostic.23", "Достигнут предел размера WAV.", "WAV size limit reached.", "WAV-Größenlimit erreicht.");
            Add("diagnostic.24", "Файл не является RIFF WAV.", "Not a RIFF WAV.", "Datei ist keine RIFF WAV.");
            Add("diagnostic.25", "Файл не является WAVE.", "Not a WAVE file.", "Datei ist keine WAVE-Datei.");
            Add("diagnostic.26", "Отсутствует формат WAV.", "Missing WAV format.", "WAV-Format fehlt.");
            Add("diagnostic.27", "Размер данных WAV не соответствует файлу.", "WAV data size does not match the file.", "WAV-Datengröße passt nicht zur Datei.");
            Add("diagnostic.28", "Неверный блок WAV.", "Invalid WAV chunk.", "Ungültiger WAV-Block.");
            Add("diagnostic.29", "Отсутствуют данные WAV.", "Missing WAV data.", "WAV-Daten fehlen.");
            Add("diagnostic.30", "Аудиопакет не выровнен по кадрам.", "Unaligned packet.", "Audiopaket nicht an Frames ausgerichtet.");
            Add("diagnostic.31", "Неожиданная длина формата аудио.", "Unexpected audio format length.", "Unerwartete Audioformatlänge.");
            Add("diagnostic.32", "Не удалось обработать буфер аудиоустройства.", "Audio device buffer did not drain.", "Audiogerätepuffer wurde nicht geleert.");
            Add("diagnostic.33", "Устройство вывода отключено.", "Output device disconnected.", "Ausgabegerät wurde getrennt.");
            Add("diagnostic.34", "Устройство вывода сменилось. Начните новую запись для нового устройства.", "Output device changed. Start a new recording for the new device.", "Ausgabegerät gewechselt. Neue Aufnahme für das neue Gerät starten.");
            Add("diagnostic.35", "Нет аудиоданных; оставлен временный WAV.", "No audio data; temporary WAV retained.", "Keine Audiodaten; temporäre WAV bleibt erhalten.");
            Add("startShort", "Начать", "Start", "Start");
            Add("pauseShort", "Пауза", "Pause", "Pause");
            Add("stopShort", "Стоп", "Stop", "Stopp");
            Add("resumeShort", "Продолжить", "Resume", "Fortsetzen");
            Add("recoverShort", "Собрать", "Recover", "Retten");
            Add("exportShort", "Создать файл", "Create file", "Neue Datei");
            Add("logShort", "Журнал", "Log", "Protokoll");
            Add("wavOnlyShort", "Только WAV", "WAV only", "Nur WAV");
            Add("captureGroup", "Запись", "Audio", "Audio");
            Add("filesGroup", "Файлы", "Files", "Dateien");
            Add("appearanceGroup", "Оформление", "Appearance", "Design");
            Add("profileInfo", "ⓘ Параметры звука", "ⓘ Audio parameters", "ⓘ Audioparameter");
            Add("on", "включён", "on", "an");
            Add("off", "выключен", "off", "aus");
            Add("previous", "Назад", "Previous", "Zurück");
            Add("next", "Далее", "Next", "Weiter");
            Add("revealShort", "В папке", "Folder", "Ordner");
            Add("convertShort", "Другой формат", "Convert", "Konvertieren");
            Add("conversionCompact", "Исходник сохранится. Качество не повысится.", "Original retained. Quality will not improve.", "Original bleibt. Qualität wird nicht verbessert.");
            foreach (var entry in entries) foreach (string value in entry.Value) if (!ids.ContainsKey(value)) ids.Add(value, entry.Key);
            // Short UI labels are translated only as complete strings, never inside diagnostic text.
            var values = new List<string>(); foreach (string value in ids.Keys) if (value.Length > 3) values.Add(value);
            values.Sort(delegate(string a, string b) { return b.Length.CompareTo(a.Length); });
            for (int i = 0; i < values.Count; i++)
            {
                string value = values[i];
                values[i] = (char.IsLetterOrDigit(value[0]) ? @"(?<![\p{L}\p{N}_])" : "") + Regex.Escape(value) +
                    (char.IsLetterOrDigit(value[value.Length - 1]) ? @"(?![\p{L}\p{N}_])" : "");
            }
            known = new Regex(string.Join("|", values.ToArray()), RegexOptions.CultureInvariant);
        }
    }
}
